vich_uploader:
    db_driver: orm

    mappings:
        meal_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
        ingredient_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
        ownerphoto_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
        image_file:
            uri_prefix: /uploads
            upload_destination: '%upload_directory%'
